version: '3.8'

services:
  postgres:
    image: postgres
    container_name: bookstore-database
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: bookstore
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres:/var/lib/postgresql/data


volumes:
  postgres: